prompts_neg = [
    "pig flying an airplane",
    "pig wearing a tuxedo",
    "pig surfing at the beach",
    "pig baking a cake",
    "pig riding a motorcycle",
    "pig painting a portrait",
    "pig dancing ballet",
    "pig playing video games",
    "pig exploring space",
    "pig building a robot",
    "pig sleeping on hammock",
    "pig swimming with dolphins",
    "pig in superhero costume",
    "pig conducting a train",
    "pig holding an umbrella",
    "pig reading bedtime story",
    "pig playing basketball",
    "pig attending a tea party",
    "pig dressed as a pirate",
    "pig hiking mountains",
    "pig selling ice cream",
    "pig gardening flowers",
    "pig juggling oranges",
    "pig fishing in river",
    "pig driving a tractor",
    "pig wearing wizard hat",
    "pig relaxing at spa",
    "pig playing saxophone",
    "pig eating spaghetti",
    "pig watching fireworks",
    "pig knitting sweater",
    "pig at the library",
    "pig running marathon",
    "pig climbing tree",
    "pig wearing sunglasses",
    "pig painting fences",
    "pig skating on ice",
    "pig riding skateboard",
    "pig traveling by train",
    "pig singing karaoke",
    "pig watering plants",
    "pig scuba diving",
    "pig celebrating birthday",
    "pig cooking pancakes",
    "pig photographing wildlife",
    "pig meditating calmly",
    "pig skiing downhill",
    "pig sitting on throne",
    "pig sailing a boat",
    "pig playing piano"
]

prompts_pos = [
    "rabbit reading a newspaper",
    "rabbit in an astronaut suit",
    "rabbit dancing in rain",
    "rabbit playing chess",
    "rabbit wearing sunglasses",
    "rabbit painting a landscape",
    "rabbit riding a bicycle",
    "rabbit cooking pancakes",
    "rabbit floating in space",
    "rabbit knitting a scarf",
    "rabbit skiing downhill",
    "rabbit driving a convertible",
    "rabbit sitting on a throne",
    "rabbit watering flowers",
    "rabbit playing guitar",
    "rabbit climbing a mountain",
    "rabbit having tea party",
    "rabbit wearing medieval armor",
    "rabbit at a campfire",
    "rabbit holding balloons",
    "rabbit diving underwater",
    "rabbit sleeping on clouds",
    "rabbit baking cookies",
    "rabbit juggling apples",
    "rabbit in a magician's hat",
    "rabbit surfing waves",
    "rabbit building a sandcastle",
    "rabbit flying a kite",
    "rabbit picking strawberries",
    "rabbit dressed as detective",
    "rabbit performing ballet",
    "rabbit exploring jungle",
    "rabbit sitting at library",
    "rabbit in hot air balloon",
    "rabbit playing drums",
    "rabbit taking photos",
    "rabbit meditating peacefully",
    "rabbit ice-skating",
    "rabbit gardening vegetables",
    "rabbit delivering mail",
    "rabbit running a marathon",
    "rabbit watching stars",
    "rabbit making pottery",
    "rabbit fishing in a pond",
    "rabbit relaxing in hammock",
    "rabbit sculpting snowman",
    "rabbit visiting museum",
    "rabbit conducting orchestra",
    "rabbit shopping at market",
    "rabbit sailing small boat"
]

prompts_neutral = [
    "castle floating in clouds",
    "robot watering plants",
    "cat drinking tea",
    "wizard reading spellbook",
    "butterfly landing on flower",
    "astronaut lost in forest",
    "sailing ship at sunset",
    "owl wearing glasses",
    "giraffe playing piano",
    "fox sleeping under moon",
    "mouse flying airplane",
    "ghost exploring library",
    "lion painting portrait",
    "dog skateboarding",
    "dragon baking bread",
    "bear fishing at lake",
    "turtle wearing hat",
    "bird singing opera",
    "unicorn eating ice cream",
    "snowman at beach",
    "robot playing violin",
    "penguin building igloo",
    "mermaid brushing hair",
    "knight riding bicycle",
    "banana dancing salsa",
    "pumpkin holding umbrella",
    "squirrel driving bus",
    "bee knitting sweater",
    "witch stirring potion",
    "monster having picnic",
    "frog writing poetry",
    "cactus wearing scarf",
    "cupcake doing yoga",
    "pirate watering garden",
    "elephant holding camera",
    "monkey climbing skyscraper",
    "flower reading newspaper",
    "dinosaur eating pizza",
    "cloud listening to music",
    "octopus playing drums",
    "apple riding scooter",
    "cow surfing waves",
    "zebra taking selfie",
    "alien hiking mountain",
    "sunflower painting sunset",
    "duck shopping vegetables",
    "mushroom playing chess",
    "horse flying balloon",
    "moon wearing sunglasses",
    "robot drinking coffee"
]